---
title: "Spatial Project"
author: "Chansoo Song"
date: "10/2/2018"
output: pdf_document
---

```{r setup, include=FALSE,warning=FALSE,message=FALSE}
knitr::opts_chunk$set(echo=TRUE,tidy=TRUE)
  library(ggplot2)
  library(dplyr)
  # devtools::install_github("dkahle/ggmap", ref = "tidyup")
  library(ggmap) # install using line above
```

## Load Data

```{r}
# Stop and Frisk Data
load('Data/stops2013clean.RData')

# CSV containing precincts and corresponding borough
prec_bor = read.csv('Data/prec_to_boroughs.csv', header = F, stringsAsFactors = F)

# Latitude and Longitude of the center of the circle containing highest number of stops
high_stops_center = read.csv('results/Manhattan_0.01_result.csv',header = T)
```

## Clean Data

```{r}
# Column names of prec_bor
colnames(prec_bor) = c('precinct','borough')

# Subset stop and frisk data
cols_to_keep = c("id",
                 "lon",
                 "lat",
                 "year",
                 "precinct",
                 "found.contraband",
                 "found.pistol",
                 "found.rifle",
                 "found.assault",
                 "found.knife",
                 "found.machinegun",
                 "found.other",
                 "found.gun",
                 "found.weapon")
df = stops2013clean[,cols_to_keep]

# Create "Hits" column in Stop and Frisk Data
cols_hit = c("found.contraband",
                 "found.pistol",
                 "found.rifle",
                 "found.assault",
                 "found.knife",
                 "found.machinegun",
                 "found.other",
                 "found.gun",
                 "found.weapon")
# hits column
df$hit = ifelse( apply(df[,cols_hit],1,sum)>0, 1, 0)

# Merge Stop and Frisk Data and Precinct_Borough Data
df$precinct = as.integer(as.character(df$precinct))
df = df %>% 
  left_join(prec_bor, by = 'precinct')

# Don't need these anymore. 
rm(stops2013clean)
rm(prec_bor)
```

## Test for Significance of Hit Rate in the High Stop Circle

```{r}
# Random sample of centers
n_samples = 999
samples_idx = sample(nrow(df), n_samples)
centers = df[samples_idx,c("id","lon","lat","hit")]

# Get Hit Rates for Circles of Fixed Radius around this random sample of centers
radius = 0.01
hit_rate = rep(NA, n_samples)
for(i in 1:n_samples){
  # Longitude and Latitude of Center
  center_lon = centers[i,c("lon")]
  center_lat = centers[i,c("lat")]
  
  # Distances between Center and All Stops
  distances = sqrt((df$lon - center_lon)^ 2 + (df$lat - center_lat)^ 2)
  
  # Hit Rate of Stops within Radius
  in_circle = ifelse(distances < radius, 1, 0)
  
  hit_rate[i] = sum(in_circle * df$hit) / sum(in_circle)
}

plot(density(hit_rate))
```

## Draw Circles

```{r}
make_circles <- function(centers, radius, nPoints = 100){
    # centers: the data frame of centers with ID
    # radius: radius measured in kilometer
    #
    # meanLat <- mean(centers$lat)
    # length per longitude changes with lattitude, so need correction
    # radiusLon <- radius /111 / cos(meanLat/57.3) 
    # radiusLat <- radius / 111
    circleDF <- data.frame(ID = rep(centers$X, each = nPoints))
    angle <- seq(0,2*pi,length.out = nPoints)

    circleDF$lon <- unlist(lapply(centers$lon, function(x) x + radius * cos(angle)))
    circleDF$lat <- unlist(lapply(centers$lat, function(x) x + radius * sin(angle)))
    return(circleDF)
}


# here is the data frame for all circles
myCircles <- make_circles(data, 0.01)
```

## Plot on Map

```{r}
register_google(key = "AIzaSyC4ABT6F3JznHUr-uCTAFs4R3lgDYNul_k")
nyc_map = get_map(location = c(lon = -73.94316, lat = 40.7965), 
                  zoom = 14, 
                  maptype = "satellite",
                  source = "google")
nycMap = ggmap(nyc_map, extent = "panel", legend = "bottomright")
nycMap

RL = geom_point(aes(x = lon, y = lat), 
                data = data, 
                color = "#ff0000")
stops = geom_point(aes(x=lon, y = lat), 
                   data = df, 
                   color = df$hit+1,
                   alpha = 0.2)

nycMap + RL + stops +
    geom_polygon(data = myCircles, aes(lon, lat, group = ID), color = "red", alpha = 0)

```












